import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'weather_model.freezed.dart';
part 'weather_model.g.dart';

@freezed
class WeatherModelResponse with _$WeatherModelResponse {
  const factory WeatherModelResponse({
    WeatherModel? location,
    WeatherModelCurrent? current,
    WeatherModelForecast? forecast,
  }) = _WeatherModelResponse;

  factory WeatherModelResponse.fromJson(Map<String, Object?> json) =>
      _$WeatherModelResponseFromJson(json);
}

@freezed
class WeatherModel with _$WeatherModel {
  const factory WeatherModel({
    String? name,
    String? country,
    String? region,
  }) = _WeatherModel;

  factory WeatherModel.fromJson(Map<String, Object?> json) =>
      _$WeatherModelFromJson(json);
}

@freezed
class WeatherModelCurrent with _$WeatherModelCurrent {
  const factory WeatherModelCurrent({
    double? temp_c,
    double? wind_kph,
  }) = _WeatherModelCurrent;

  factory WeatherModelCurrent.fromJson(Map<String, Object?> json) =>
      _$WeatherModelCurrentFromJson(json);
}

@freezed
class WeatherModelForecast with _$WeatherModelForecast {
  const factory WeatherModelForecast({
    List<WeatherDay>? forecastday,
  }) = _WeatherModelForecast;

  factory WeatherModelForecast.fromJson(Map<String, dynamic> json) =>
      _$WeatherModelForecastFromJson(json);
}

@freezed
class WeatherDay with _$WeatherDay {
  const factory WeatherDay({
    String? date,
    WeatherDayDetails? day,
  }) = _WeatherDay;

  factory WeatherDay.fromJson(Map<String, dynamic> json) =>
      _$WeatherDayFromJson(json);
}

@freezed
class WeatherDayDetails with _$WeatherDayDetails {
  const factory WeatherDayDetails({
    double? maxtemp_c,
    double? mintemp_c,
  }) = _WeatherDayDetails;

  factory WeatherDayDetails.fromJson(Map<String, dynamic> json) =>
      _$WeatherDayDetailsFromJson(json);
}
