import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'weather_model.freezed.dart';
part 'weather_model.g.dart';

@freezed
class WeatherModelResponse with _$WeatherModelResponse {
  const factory WeatherModelResponse({
    WeatherModel? location,
  }) = _WeatherModelResponse;

  factory WeatherModelResponse.fromJson(Map<String, Object?> json)
  => _$WeatherModelResponseFromJson(json);
}

@freezed
class WeatherModel with _$WeatherModel {
  const factory WeatherModel({
     String? name,
     String? country,
  }) = _WeatherModel;

  factory WeatherModel.fromJson(Map<String, Object?> json)
  => _$WeatherModelFromJson(json);
}

